Application.Web/Controllers/RelatorioController.cs
using Application.Web.Models;
using Domain.Entities;
using Domain.Interfaces.Entidades;
using Domain.Repositorios.Entidades;
using Microsoft.AspNetCore.Mvc;

namespace Application.Web.Controllers
{
	public class RelatorioController : Controller
	{
		private readonly ILogger<RelatorioController> _logger;
		private readonly IMovimentacaoServico _movimentacaoService;

		public RelatorioController(ILogger<RelatorioController> logger, IMovimentacaoServico movimentacaoService)
		{
			_logger = logger;
			_movimentacaoService = movimentacaoService;
		}

		public IActionResult Index()
		{
			var ret = new RelatorioViewModel();
			ret.DataDe = new DateTime(2020,01,01);
			ret.DataAte = DateTime.Today;
			return View(ret);
		}

		[HttpPost]
		public IActionResult Index(RelatorioViewModel model)
		{
			var ret = new RelatorioViewModel();
			ret.Relatorio = new List<DadosRelatorio>();

			//var movimentacoes = _movimentacaoService.GetProc("GerarRelatorio", "@DataDe,@DataAte,@Tipo,@FornecedorId,@MaterialId");
			//var lst = movimentacoes.Select(x => new Items()
			//{
			//	Data = x.Data,
			//	MaterialCodigo = x.MaterialCodigo,

			//	QtdEntrada = x.QtdEntrada,
			//	ValorEntrada = x.ValorEntrada,

			//	QtdSaida = x.QtdSaida,
			//	ValorSaida = x.ValorSaida,

			//	QtdSaldo = x.QtdEntrada - x.QtdSaida,
			//	ValorSaldo = x.ValorEntrada - x.ValorSaida

			//}).ToList();
			var movimentacoes = _movimentacaoService.GetAll()
				.Where(d => (model.TipoMovimentacao == 0 || d.Tipo == model.TipoMovimentacao) &&
						   (model.FornecedorId == 0 || d.Fornecedor?.Id == model.FornecedorId) &&
						   (model.MaterialId == null || d.Material?.Id == model.MaterialId) &&
						   (model.DataDe <= d.Data) &&
						   (model.DataAte >= d.Data))
				.ToList();

			var lst = movimentacoes.Select(x => new Items()
			{
				Data = x.Data,
				MaterialCodigo = x.Material.Codigo,

				QtdEntrada = x.Tipo == Domain.Enums.ETipoMovimentacao.Entrada ? x.Quantidade : 0,
				ValorEntrada = x.Tipo == Domain.Enums.ETipoMovimentacao.Entrada ? x.ValorTotal : 0,

				QtdSaida = x.Tipo == Domain.Enums.ETipoMovimentacao.Saida ? x.Quantidade : 0,
				ValorSaida = x.Tipo == Domain.Enums.ETipoMovimentacao.Saida ? x.ValorTotal : 0,

				QtdSaldo = x.Quantidade,
				ValorSaldo = x.ValorTotal

			}).ToList();



			ret.Relatorio = lst.GroupBy(x => x.MaterialCodigo)
				.Select(X => new DadosRelatorio()
				{
					MaterialCodigo = X.Key,
					QtdTotalEntrada = X.Sum(D => D.QtdEntrada),
					ValorTotalEntrada = X.Sum(D => D.ValorEntrada),
					QtdTotalSaida = X.Sum(D => D.QtdSaida),
					ValorTotalSaida = X.Sum(D => D.ValorSaida),

					QtdTotaldSaldo = X.Sum(D => D.QtdEntrada) - X.Sum(D => D.QtdSaida),
					ValorTotalSaldo = X.Sum(D => D.ValorEntrada) - X.Sum(D => D.ValorSaida),
					MovimentacoesMaterial = X.ToList(),

				}).ToList();

			return View(ret);
		}

		public IActionResult Privacy()
		{
			return View();
		}

	}
}

Application.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Teste - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Application.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Applicação Teste</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Fornecedor" asp-action="Index">Cadastrrar Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Material" asp-action="Index">Cadastrar Materiais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Movimentacao" asp-action="Index">Movimentar Estoque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Relatorio" asp-action="Index">Gerar Relatório</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @RenderSection("Formulario", required: false)
            
            @RenderSection("Listagem", required: false)
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Application.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>